//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Memcomb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connection
    {
        public int Connection_ID { get; set; }
        public int Fragment_One_ID { get; set; }
        public int User_One_ID { get; set; }
        public int Fragment_Two_ID { get; set; }
        public int User_Two_ID { get; set; }
    
        public virtual Fragment Fragment { get; set; }
        public virtual User User { get; set; }
    }
}
