//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Memcomb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class memcombdbEntities : DbContext
    {
        public memcombdbEntities()
            : base("name=memcombdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Connection> Connections { get; set; }
        public virtual DbSet<Convo> Convoes { get; set; }
        public virtual DbSet<Following> Followings { get; set; }
        public virtual DbSet<Fragment> Fragments { get; set; }
        public virtual DbSet<Memory> Memories { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Blocking> Blockings { get; set; }
        public virtual DbSet<Flag> Flags { get; set; }
        public virtual DbSet<Like> Likes { get; set; }
    }
}
