//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Memcomb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Memory
    {
        public int Memory_ID { get; set; }
        public int User_ID { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public string Memory_Title { get; set; }
        
        [DataType(DataType.MultilineText)]
        public string Memory_Description { get; set; }
    }
}
