//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Memcomb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int User_ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Email_ID { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public string Phone_Number { get; set; }
        public string Profile_Picture { get; set; }
        public string Biography { get; set; }
        public bool Is_Verified { get; set; }
        public string Activation_Code { get; set; }
        public bool Is_Admin { get; set; }
    }
}
